apiVersion: v1
kind: Service
metadata:
  labels:
    app:  httpd-svc
  name:  httpd-svc
  namespace: httpd 
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app:  httpd-deployment